<a href="https://colab.research.google.com/github/pravindeva/python/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
print(torch.__version__)

1.1.0


In [0]:
#torch.tensor
import torch
import numpy as np


In [0]:
list2=([1,2,3,4,5])
ex_tensor=torch.tensor(list2)

In [0]:
ex_tensor

tensor([1, 2, 3, 4, 5])

In [0]:
type(ex_tensor)

torch.Tensor

In [0]:
np_tensor=torch.tensor(np.array([1,2,3,4,5,6,7,8,9,9,9,88,0]))
np_tensor 

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  9,  9, 88,  0])

In [0]:
type(np_tensor)

torch.Tensor

In [0]:
#data type=dtype
tensor_float=torch.tensor([3,4,5],dtype=torch.float32)

In [0]:
tensor_float


tensor([3., 4., 5.])

In [0]:
#other important parameter for torch.tensor -Device and reuires_grad

In [0]:
#ones
x=torch.ones((3,2),dtype=torch.int32)
print(x)

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)


In [0]:
#zeros
y=torch.zeros((5,2))
y

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [0]:
#torch.rand
torch.rand(3,4)

tensor([[0.9213, 0.4393, 0.6453, 0.3260],
        [0.1736, 0.6693, 0.8693, 0.2657],
        [0.8449, 0.6826, 0.1388, 0.9929]])

In [0]:
torch.arange(4,64,4)

tensor([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60])

In [0]:
#empty

In [0]:
torch.empty(3,4
        )

tensor([[8.2696e-37, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 1.8854e-13, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])

In [0]:
#identical marix torch.eye
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [2]:
import torch
example=torch.arange(8)
example

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
example.shape

torch.Size([8])

In [6]:
#view
example.view(8,1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]])

In [7]:
#reshape
example.reshape(4,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [9]:
ex2=torch.arange(8).reshape(4,2)
ex2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [11]:
ex2[2,1]

tensor(5)

In [12]:
ex2[2,1].item()

5

In [15]:
ex2[:,1]

tensor([1, 3, 5, 7])

In [16]:
ex2[0,:]

tensor([0, 1])

In [17]:
ex2[1,:].item()#show error

ValueError: ignored